# Generated by Django 5.0.3 on 2024-03-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0002_message_delete_massages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Messages',
        ),
    ]
